name: tictactoe-mern

services:
  database:
    image: mongo:7.0
    container_name: tictactoe-mern-database
    ports:
      - 27017:27017
    volumes:
      - tictactoe-mern-data:/data/db

volumes:
  tictactoe-mern-data:
